name: abiotic-factor
services:
  dedicated-server:
    image: "ghcr.io/cevataykans/abiotic-factor-macos-docker:latest"
    restart: unless-stopped
    volumes:
      - "./Saved:/home/abiotic/abioticserver/AbioticFactor/Saved"
    environment:
      UsePerfThreads: true
      DisableAsyncLoadingThread: false
      MaxServerPlayers: 6
      # TODO: CHANGE PASSWORD FOR YOUR SERVER
      ServerPassword: "password"
      # TODO: CHANGE NAME THAT APPEARS IN SERVER BROWSER
      SteamServerName: "Dedicated Server"
      # TODO: CHANGE ADMIN PASSWORD FOR YOUR SERVER (or leave as blank for disabling admin password)
      AdminPassword: "admin"
      WorldSaveName: "Cascade"
      OverrideSandboxPath: "-SandboxIniPath=DefaultSandboxSettings.ini"
      OverrideAdminPath: "-AdminIniPath=Admin.ini"
      AdditionalArgs: ""
    ports:
      - "0.0.0.0:7777:7777/udp"
      - "0.0.0.0:7777:7777/tcp"
      - "0.0.0.0:27015:27015/udp"
      - "0.0.0.0:27015:27015/tcp"